export const moviesHeroInfo = [
  {
    adult: false,
    backdrop_path: "/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 19995,
    original_language: "en",
    original_title: "Avatar",
    overview:
      "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
    popularity: 32.1843,
    poster_path: "/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
    release_date: "2009-12-15",
    title: "Avatar",
    video: false,
    vote_average: 7.591,
    vote_count: 32445,
    imgLocal: "/avatar.webp",
  },
  {
    adult: false,
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    genre_ids: [
        12,
        878,
        28
    ],
    id: 299534,
    original_language: "en",
    original_title: "Avengers: Endgame",
    overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    popularity: 18.9453,
    poster_path: "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    release_date: "2019-04-24",
    title: "Avengers: Endgame",
    video: false,
    vote_average: 8.239,
    vote_count: 26562,
    imgLocal: "/avengers.webp",
},
  {
    adult: false,
    backdrop_path: "/yY76zq9XSuJ4nWyPDuwkdV7Wt0c.jpg",
    genre_ids: [28, 53, 878],
    id: 577922,
    original_language: "en",
    original_title: "Tenet",
    overview:
      "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    popularity: 9.473,
    poster_path: "/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
    release_date: "2020-08-22",
    title: "Tenet",
    video: false,
    vote_average: 7.179,
    vote_count: 10369,
    imgLocal: "/tenet.webp",
  },
];
